Task 1 dev
AJMC2002/Window-Apps pull request #1
Opened 2022-10-17 20:28 UTC by AJMC2002

2022-10-18 03:24 UTC, 8symbols requested changes
У вас не должно быть папки "Task 1". В ветке `main` находится код вашего проекта, в ветках `task-*` - код проекта с выполненным заданием. После сдачи задания его код сливается в основную ветку. Поэтому никаких папок с заданиями быть не должно.

Удалите в ветке `main` все, кроме `.gitignore` и `readme.md`, а в ветке `task-1-dev` оставтье только содержимое папки "Task 1" (то есть удалите все, кроме папки "Task 1", ее содержимое переместите в корень, и удалите папку "Task 1")

2022-10-18 05:35 UTC, AJMC2002 commented
Сделаны изменения

2022-10-19 07:28 UTC, 8symbols requested changes
1. Укажите в readme.md длину строки, на которую рассчитан форматтер.
2. Почистите pubspec от комментариев.
3. Баг: в текстовое поле в диалоге нельзя ввести больше 40 символов. Ввести больше 40 должно быть можно, но при попытке применить должна появляться ошибка.
4. Баг: если после применения фильтров (скрыть выполненные/скрыть неизбранные) остается пустой список задач, то отображается пустой экран, а не картинка.
5. Баг: чекбокс и кнопка избранного не по центру текста:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/32729802/196617563-12cce4fa-8e53-4e96-bee9-e0478b803e54.png">

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +class TaskApp extends StatelessWidget {
В отдельный файл

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +class TaskHomePage extends StatefulWidget {
Вместе со стейтом в отдельный файл

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +  String topic = 'Учёба';
```suggestion
  String _topic = 'Учёба';
```

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +  final _formKey = GlobalKey<FormState>();
Почему здесь ключ формы? На экране нет текстовых полей. Они есть в диалогах. Это поле должно быть вынесено в виджет диалога

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +  int flag = 0;
Имя переменной не несет в себе никакой смысловой нагрузки. Более того, оно запутывает: почему флаг - `int`, а не `bool`? Назовите переменную так, чтобы имя отражало ее суть

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +  List<String> taskTitles = [];
Зачем на каждое поле создавать отдельный массив? Создайте модель задачи со всеми нужными полями

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +  String topic = 'Учёба';
Остальные поля и методы тоже сделайте приватными

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +      case 'Hide completed':
Свитч по строке - достаточно неудобное и приводящее к багам решение. Например, можно опечататься, и тогда обработчик не будет работать. Свитчи лучше делать по `enum`. Можете создать енам пунктов в выпадающем меню, и делать `PopupMenuButton` не по `String`, а по этому енаму. А лучше - вообще убрать свитч. Для этого можно сделать свою модель пункта меню, у которой будут поля с иконкой, с названием и с коллбеком на нажатие. Тогда вы сделаете `PopupMenuButton` по этой вашей модели, а затем в обработчике будете просто вызывать коллбек у полученной `value`. Тогда верстка пункта меню не будет оторвана в коде от ее логики

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +          flag += (flag % 2 == 0) ? 1 : -1;
Зачем нужны эти нечитаемые ребусы? Зачем объединять два независимых условия в одну переменную? Просто заведите два флага (`shouldHideCompleted` и `shouldHideUnfavorite`) и работайте с ними

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +        showDialog(
`popUpMenuOnClick` выходит очень жирным методом. Эти обработчики вынести в отдельные методы для лучшей читаемости

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +            title: const Center(child: Text('Подтвердите удаление')),
Диалог стоит вынести в отдельный виджет

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +                        taskIsDone.removeAt(i);
Квадратное удаление сразу по нескольким массивом. Был бы один массив с моделью задания, вы бы просто за линию сделали 
`tasks.removeWhere((task) => task.isCompleted)`;

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +                  Navigator.pop(context, 'Ок');
Зачем возвращаемое значение в навигаторе?

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +                autovalidateMode: AutovalidateMode.onUserInteraction,
Не думаю, что имеет смысл валидировать при вводе каждого символа

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +          builder: (context) => AlertDialog(
В отдельный виджет

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +                onPressed: () => Navigator.pop(context, 'Отмена'),
Аналогичный вопрос по возвращаемому значению

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +  void callback(bool state) {
Назовите метод и параметр в соответствии с их сутью

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +      builder: (context) => AlertDialog(
В отдельный виджет

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +          style: const TextStyle(fontSize: 30),
Зачем?

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +                    {
А что вам мешает сразу сделать массив `PopupMenuItem`, без предварительных джейсонок?

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +                      'icon': const Icon(Icons.check_circle)
Иконки тоже меняются

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +                      .toList())
```suggestion
                      .toList(),)
```

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +                        'assets/todolist_background.svg',
Нужно создать абстрактный класс путей к ассетам и там в статических полях объявить эти пути

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +                      style: TextStyle(fontSize: 30),
Выглядит не очень. И отступов нет, упирается прямо в край экрана. И выравнивание бы по центру сделать

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +          ? Center(
Пустое состояние бы в отдельный виджет вынести

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +                  const Flexible(
Зачем вам `Flexible`?

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +class TaskList extends StatefulWidget {
В отдельный файл

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +  final favIcon = const Icon(Icons.star_border_purple500_outlined,
`static const`. И не здесь, а в стейте

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +        itemBuilder: (context, index) => taskBuilder(validIdx[index]),
Карточку задачи вынести в отдельный виджет

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +    for (var i = 0; i < widget.taskTitles.length; i++) {
В билде не должно быть логики по фильтрации. Билд должен просто взять и отобразить готовый список, не нужно давать ему дополнительную ответственность и накладные расходы

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +  ClipRect taskBuilder(int index) {
```suggestion
  Widget taskBuilder(int index) {
```
Не нужно без надобности конкретизировать

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +            child: Transform.scale(
Зачем вам `Transform.scale`?

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +        key: UniqueKey(),
`Dismissible` принимает ключ не просто так. Он должен однозначно сопоставлять виджеты между билдами. `UniqueKey` каждый билд выдает уникальный ключ, то есть `Dismissible` будет считать, что это новый виджет, и пересоздаст все свое содержимое. Вместо этого используйте в ключе что-то, что однозначно идентифицирует вашу задачу, например, ее идентификатор

2022-10-19 07:28 UTC, 8symbols commented on lib/main.dart
> +            widget.taskTitles.removeAt(index);
Изменение полученных сверху мутабельных данных - плохая практика. Во-первых, вы не знаете, дали вам исходный массив или какую-то его копию. Во-вторых, потом будет очень сложно отследить, где кто что менял в этом массиве. Лучше сделайте коллбек на удаления и определите его в экране

2022-11-22 12:54 UTC, 8symbols requested changes
1. Баг: если отображать только избранные и в списке задач поменять у задачи статус избранности, то она не пропадет из списка задач. Аналогично с выполненными задачами.
2. Баг: если создать две задачи с одинаковым именем (например, "1"), а затем дисмисснуть верхнюю, то будет выброшено исключение.
3. Добавьте надписи "На данный момент задачи отсутствуют" отступы и сделайте выравнивание текста по центру.
4. Не помещается предупреждение об ошибке:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/32729802/203317242-23a095b9-0130-42eb-a5df-a6f4a93ab4e1.png">

5. Избавьтесь от использования глобального ключа списка задач.
6. Сепараторы между задачами кажутся лишними, портят анимацию дисмисса. В задании эти линии статичны и не зависят от списка, если вдруг вы добавили эти сепараторы из-за задания.
7. Анимация пустого списка задач клевая

2022-11-22 12:54 UTC, 8symbols commented on pubspec.yaml
> +  cupertino_icons: ^1.0.2
Если вы это не используете, удалите

2022-11-22 12:54 UTC, 8symbols commented on lib/main.dart
> +class TaskApp extends StatelessWidget {
Все еще актуально

2022-11-22 12:54 UTC, 8symbols commented on lib/main.dart
> +      home: const TaskHomePage(),
Это не совсем `TaskHomePage`. Это экран ветки задач (веток задач может быть много). Должно называться `TaskBranchScreen`, `TaskCategoryScreen` или как-то так

2022-11-22 12:54 UTC, 8symbols commented on lib/models/task.dart
> +  Task(this.title)
```suggestion
  Task({required this.title, this.isDone = false, this.isFav = false,})
```

2022-11-22 12:54 UTC, 8symbols commented on lib/models/task.dart
> +  bool isFav;
```suggestion
  bool isFavorite;
```

2022-11-22 12:54 UTC, 8symbols commented on lib/models/task.dart
> +  int? index;
Непонятно, что это за индекс и почему он nullable. Его здесь быть не должно. Используйте вместо этого `String id`, генерируемый через uuid.v4(): https://pub.dev/packages/uuid

2022-11-22 12:54 UTC, 8symbols commented on lib/models/task.dart
> +    title = newTitle;
Зачем нужны эти методы? Поля и так публичные

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/home.dart
> +  // bool _isTaskListEmpty = false;
Комментарии лишние, нужно убрать

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/home.dart
> +  final TaskListKey _taskListKey = TaskListKey();
Не нужно использовать глобальные ключи. Вместо этого передавайте коллбеки. Список задач должен храниться в _TaskHomePageState

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/home.dart
> +  final ValueNotifier<bool> _isTaskListEmpty = ValueNotifier(false);
А если изначально задачи будут? От этого ValueNotifier тоже нужно избавиться. Будете хранить данные в _TaskHomePageState, при вызове коллбеков изменять их и вызывать setState. Тогда и ValueListenableBuilder не понадобится

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/add_task_dialog.dart
> +  final _formFieldKey = GlobalKey<FormFieldState>();
В StatelessWidget не должны создаваться данные. Это поле будет пересоздаваться каждый билд. Сделайте виджет Stateful и вынесите создание поля в State

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/add_task_dialog.dart
> +  final _maxTopicLength = 40;
```suggestion
  static const _maxTopicLength = 40;
```

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/add_task_dialog.dart
> +      )),
```suggestion
      ),),
```

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/add_task_dialog.dart
> +        buildCounter: (
Это не нужно делать явно. Можно задать максимальную длину в текстовом поле, тогда этот счетчик появится сам

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/appbar.dart
> +  final Function switchRequireNotDone;
```suggestion
  final VoidCallback switchRequireNotDone;
```
Указывайте полную сигнатуру методов

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/appbar.dart
> +  final Size preferredSize;
```suggestion
  final Size preferredSize = const Size.fromHeight(kToolbarHeight);
```

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/appbar.dart
> +class HomeAppBar extends StatefulWidget implements PreferredSizeWidget {
Имя файла не соответствует имени файла

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/appbar.dart
> +  showDone, // Hide/Show Done
```suggestion
  toggleHideDone, // Hide/Show Done
```

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/appbar.dart
> +  onlyFav, // Only Favourites
```suggestion
  toggleHideNonFavorite, // Only Favourites
```

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/appbar.dart
> +class HomePopUpMenu extends StatelessWidget {
Енам и все последующие классы в этом файле нужно вынести в отдельные файлы

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/appbar.dart
> +          onFieldSubmitted: (input) => _formFieldKey.currentState!.save()),
```suggestion
          onFieldSubmitted: (input) => _formFieldKey.currentState!.save(),),
```

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/bg.dart
> +class HomeBackground extends StatelessWidget {
```suggestion
class EmptyTaskList extends StatelessWidget {
```

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/bg.dart
> +          )),
```suggestion
          ),),
```

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/bg.dart
> +                SvgPicture.asset('assets/todolist_background.svg'),
Нужно создать абстрактный класс путей к ресурсам и там в статичных полях указать пути к ним

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/bg.dart
> +      builder: ((context, child) => ClipPath(
`ClipRRect` вас не устроил?

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/task_list.dart
> +    for (int index = _tasks.length - 1; index >= 0; index--) {
Удаление у вас выполняется за квадрат. Вместо этого используйте
```
_tasks.removeWhere((task) => task.isDone);
```

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/task_list.dart
> +          _tasks[i].index = i;
От этого костыля нужно избавиться. Вместо этого работайте по идентификаторам

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/task_list.dart
> +class _TaskTile extends StatefulWidget {
В отдельный файл

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/task_list.dart
> +  final Icon _favIcon = const Icon(Icons.star_border_purple500_outlined,
```suggestion
  static const _favoriteIcon = Icon(Icons.star_border_purple500_outlined,
```

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/task_list.dart
> +        child: ListTile(
Используйте Row

2022-11-22 12:54 UTC, 8symbols commented on lib/screens/home/widgets/task_list.dart
> +        key: Key(widget.task.title),
Заголовок неуникален. Используйте идентификатор

2022-12-12 21:49 UTC, AJMC2002 commented on lib/screens/home/widgets/bg.dart
> +      builder: ((context, child) => ClipPath(
Я анимировал актив todolist, поднимающийся перед фоном, поэтому я обрезал круглую нижнюю часть и оставил остальную часть в виде прямоугольника (что-то вроде формы щита).
Я не мог придумать другого способа, но создать собственный клипер было не так уж сложно.

2022-12-12 23:48 UTC, 8symbols requested changes
1. Имена файлов должны соответствовать именам классов в них. Например, BranchPage - branch_page.dart.
2. Лучше сделать все поля у Task final, чтобы не пришлось все переделывать в следующих заданиях.

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/branch.dart
> +  String topic;
```suggestion
  final String topic;
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/branch.dart
> +      for (var i = 0; i < _allTasks.length; i++) {
```
      _allTasks.where((task) => task.id == id).forEach((task) {
        task.isDone = !task.isDone;
      });
```
А в вашем случае, скорее
```
      final task = _allTasks.singleWhere((task) => task.id == id);
      task.isDone = !task.isDone;
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/branch.dart
> +  late final List<Task> _validTasks = [];
Они не совсем `valid`, скорее, `displayed`

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/branch.dart
> +  late final List<Task> _validTasks = [];
```suggestion
 final List<Task> _validTasks = [];
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/branch.dart
> +  late final List<Task> _validTasks = [];
Объявите в начале класса сначала все поля, потом методы

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/branch.dart
> +          if (!(_requireNotDone && _allTasks[i].isDone) &&
Не очень читаемо и поддерживаемо

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/branch.dart
> +      body: Stack(
Стек лишний
```_validTasks.isEmpty ? const EmptyTaskList() : TaskList(...),```

2022-12-12 23:48 UTC, 8symbols commented on lib/models/task.dart
> +  final String id = _uuid.v4();
Лучше айдишник генерировать не в модели, а сюда просто передавать в конструкторе, как все остальные поля

2022-12-12 23:48 UTC, 8symbols commented on lib/models/task.dart
> +  bool isDone;
Лучше все поля сделать финальными, чтобы модель была имутабельная. В будущем будет проще

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/appbar.dart
> +class BranchAppBar extends StatefulWidget implements PreferredSizeWidget {
Виджет выглядит избыточно

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/bg.dart
> +abstract class _EmptyTaskListAssets {
Этот класс должен быть в отдельном файле

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/bg.dart
> +  final double _size = 181;
```suggestion
  static const _size = 181;
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/bg.dart
> +          )),
```suggestion
          ),),
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/bg.dart
> +    return true;
```suggestion
    return false;
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/edit_topic_dialog.dart
> +  final int _maxTopicLength = 40;
```suggestion
  static const _maxTopicLength = 40;
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/edit_topic_dialog.dart
> +  final _formFieldKey = GlobalKey<FormFieldState>();
В StaltelessWidget нельзя создавать данные, потому что они могут пересоздаваться каждый билд. Сделайте виджет Stateful и вынесите поле в State

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/add_task_dialog.dart
> +  final _formFieldKey = GlobalKey<FormFieldState>();
Сделать Stateful и вынести в State

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/appbar/appbar.dart
> +class BranchAppBar extends StatefulWidget implements PreferredSizeWidget {
Виджет выглядит избыточно

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/appbar/edit_topic_dialog.dart
> +  final int _maxTopicLength = 40;
```suggestion
  static const _maxTopicLength = 40;
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/appbar/edit_topic_dialog.dart
> +  final _formFieldKey = GlobalKey<FormFieldState>();
В StatelessWidget не должно быть создания данных, потому что они пересоздаются каждый билд. Сделайте StatefulWidget и вынесите в State

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/appbar/popupmenu.dart
> +  toggleHideDone, // Hide/Show Done
```suggestion
  /// Документирующие комментарии пишутся вот так.
  toggleHideDone,
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/appbar/popupmenu.dart
> +      case _BranchPopMenuItem.toggleHideDone:
Не очень удобно отделять визуальное представление пункта меню от его обработчика. Можно сделать PopupMenuButton не по _BranchPopMenuItem, а по какому-нибудь PopupMenuItemData, где PopupMenuItemData - ваш класс, который содержит иконку, заголовок, и коллбек на нажатие, и тогда вы бы могли написать
```
onSelected: (value) => value.onTap(),
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/fab/add_task_dialog.dart
> +  final _formFieldKey = GlobalKey<FormFieldState>();
В State

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/empty_tasklist.dart
> +  final double _size = 181;
```suggestion
  static const _size = 181;
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/empty_tasklist.dart
> +          )),
```suggestion
          ),),
```

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/empty_tasklist.dart
> +abstract class _EmptyTaskListAssets {
Этот класс должен быть публичным и в отдельном файле

2022-12-12 23:48 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/empty_tasklist.dart
> +    return true;
```suggestion
    return false;
```

2022-12-12 23:51 UTC, 8symbols commented on lib/screens/branch/branch.dart
> +          if (!(_requireNotDone && _allTasks[i].isDone) &&
Как вариант, можно делать фильтрацию навешиванием итераторов:
```
  void _filter() {
    setState(() {
      Iterable<Task> shownTasksIterable = _tasks;
      if (_onlyFavoriteShown) {
        shownTasksIterable = shownTasksIterable.where((task) => task.isFavorite);
      }
      if (_onlyIncompleteShown) {
        shownTasksIterable = shownTasksIterable.where((task) => !task.isCompleted);
      }
      _shownTasks = shownTasksIterable.toList();
    });
  }
```

2022-12-13 16:17 UTC, AJMC2002 commented on lib/models/task.dart
> +  bool isDone;
Тогда как мне изменить, когда задача выполнена или нет, например?

2022-12-14 04:05 UTC, 8symbols commented on lib/models/task.dart
> +  bool isDone;
Создавать новый объект.
В Task написать метод для копирования, например, такой:
```
Task copyWith({String? title, bool? isDone, ...}) {
   return Task(
      title: title ?? this.title,
      isDone: isDone ?? this.isDone,
      ...
   );
}
```
или использовать кодогенерацию из какого-нибудь freezed.

Затем изменять данные в массиве:
```
_allTasks[i] = _allTasks[I].copyWith(isDone: !_allTasks[i].isDone);
```

2022-12-17 08:50 UTC, 8symbols approved these changes
Хорошая работа, зачтено. Устраните замечания (на ревью потом звать не нужно), сливайте в main и делайте от main ветку, в которой будете выполнять второе задание

2022-12-17 08:50 UTC, 8symbols commented on .gitignore
> +lib/screens/todo/todo.dart
Почему это в гитигноре? Такого не должно быть, выглядит как неправильное использование гита, нужно убрать

2022-12-17 08:50 UTC, 8symbols commented on lib/task_app.dart
> +      home: const BranchPage(topic: "Учёба", uuid: Settings.uuid),
```suggestion
      home: const BranchPage(topic: 'Учёба', uuid: Settings.uuid),
```

2022-12-17 08:50 UTC, 8symbols commented on lib/settings.dart
> +  static const uuid = Uuid();
`Settings`- это больше про пользовательские настройки. Настройки конфигурации обычно называют `Config`.

Не уверен, что от вынесения uuid в статичное поле стало принципиально лучше, чем если бы вы просто при необходимости не писали `const Uuid().v4` Если уж идти в абстрации и зависимости, то надо создавать сущность, которая бы генерировала идентификаторы, а про ее реализацию клиенты ничего бы не знали. А так у вас есть зависимость на uuid. Плюс вашего подхода в том, что можно менять опции `Uuid` в одном месте кодовой базы, но поскольку вам это не требуется, выглядит как оверинжениринг.

Можете оставить все как есть, разве что класс лучше переименовать в `Config`

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/todo/todo_page.dart
> +class TODOPage extends StatefulWidget {
Если код не используется, его нужно удалить. Этот класс не используется

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/todo/todo_page.dart
> +class TODOPage extends StatefulWidget {
```suggestion
class TaskPage extends StatefulWidget {
```
Вы же в остальных местах задачу называете `Task`

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/task_list_background.dart
> +          ((MediaQuery.of(context).size.height - 25) / 77).floor() - 1,
При открытии клавиатуры вылетает ошибка:
`A RenderFlex overflowed by 6.7 pixels on the bottom.`

Попробуйте вместо Column использовать `ListView` с `physics: const NeverScrollableScrollPhysics()`.

Выражение нужно упростить. Как минимум, вынести `25` и `77` в константы, чтобы у них были имена, потому что сейчас непонятно, откуда эти магические числа берутся.

Поскольку с `ListView` вы сможете указывать больше элементов, чем поместится на экране, можно будет написать выражение вида `(MediaQuery.of(context).size.heigh ~/ widgetHeight + 1`

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/task_tile.dart
> +class TaskTileState extends State<TaskTile> {
Зачем тут состояние? `TaskTile` может быть `StatelessWidget`

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/task_list.dart
> +        bottom: kFloatingActionButtonMargin + 65,
Магическое число `65`. Вынести в константу (или константы), чтобы было понимание, как и из чего оно образовалось

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/empty_task_list_assets.dart
> +abstract class EmptyTaskListAssets {
```suggestion
abstract class Assets {
```

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/empty_task_list_assets.dart
> +  static const String todolistBackground = 'assets/todolist_background.svg';
```suggestion
  static const todolistBackground = 'assets/todolist_background.svg';
```

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/empty_task_list_assets.dart
> +  static const String todolist = 'assets/todolist.svg';
```suggestion
  static const todolist = 'assets/todolist.svg';
```

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/empty_task_list.dart
> +    var path = Path();
```suggestion
    final path = Path();
```

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/tasklist/empty_task_list.dart
> +      ..addListener(() {})
```suggestion
```

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/appbar/branch_popupmenu.dart
> +            const Duration(seconds: 0),
```suggestion
            Duration.zero,
```

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/appbar/branch_popupmenu.dart
> +          onTap: () => Future.delayed(
Лучше создать внутри этого класса метод, который будет принимать другой метод и вызывать его в Future.delayed, чтобы эта логика была в одном месте. Также нужно добавить перед этой Future `//комментарий` с пояснением, почему она тут нужна

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/widgets/appbar/branch_popupmenu.dart
> +        PopupMenuItem(
Сложно фокусироваться, когда код в одном большом методе. Лучше иметь несколько небольших методов:
```
 itemBuilder: (context) => [
    _buildSwitchRequireNotDonePopUpItem(context),
    // ...
    _buildEditTopicPopUpItem(context),
],
```

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/branch_page.dart
> +      floatingActionButton: FloatingActionButton(
Билд FloatingActionButton стоит в отдельный метод вынести

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/branch_page.dart
> +      body: Stack(
Билд body стоит в отдельный метод вынести

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/branch_page.dart
> +          BranchPopUpMenu(
Билд BranchPopUpMenu стоит в отдельный метод вынести:
```
actions: [
    _buildBranchPopUpMenu(),
],
```

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/branch_page.dart
> +    setState(() {});
Лучше весь код этого метода поместить в коллбек setState, чтобы было явно указано, что изменилось

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/branch_page.dart
> +    int i = _getIndex(id);
```suggestion
   final i = _getIndex(id);
```

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/branch_page.dart
> +    int i = _getIndex(id);
```suggestion
    final i = _getIndex(id);
```

2022-12-17 08:50 UTC, 8symbols commented on lib/screens/branch/branch_page.dart
> +    _topic = newTopic;
Это нужно делать перед вызовом setState, а лучше - внутри его коллбека

2022-12-21 02:03 UTC, merged